# Use an official Node.js runtime as a base image
FROM node:16
# Set the working directory in the container
WORKDIR /usr/src/app
# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
# Install the application dependencies
RUN npm install --production
# Copy the application code into the container
COPY . .
# Expose the port your app will run on
EXPOSE 3000
# Define the command to run your application
CMD ["node", "app.js"]